package de.greendao.daoexample;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CITY.
 */
public class City {

    private Long id;
    /** Not-null value. */
    private String cityName;
    private String city;
    private Long cityId;

    public City() {
    }

    public City(Long id) {
        this.id = id;
    }

    public City(Long id, String cityName, String city, Long cityId) {
        this.id = id;
        this.cityName = cityName;
        this.city = city;
        this.cityId = cityId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCityName() {
        return cityName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public Long getCityId() {
        return cityId;
    }

    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

}
