package de.greendao.daoexample;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig privinceCityDaoConfig;
    private final DaoConfig cityDaoConfig;

    private final PrivinceCityDao privinceCityDao;
    private final CityDao cityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        privinceCityDaoConfig = daoConfigMap.get(PrivinceCityDao.class).clone();
        privinceCityDaoConfig.initIdentityScope(type);

        cityDaoConfig = daoConfigMap.get(CityDao.class).clone();
        cityDaoConfig.initIdentityScope(type);

        privinceCityDao = new PrivinceCityDao(privinceCityDaoConfig, this);
        cityDao = new CityDao(cityDaoConfig, this);

        registerDao(PrivinceCity.class, privinceCityDao);
        registerDao(City.class, cityDao);
    }
    
    public void clear() {
        privinceCityDaoConfig.getIdentityScope().clear();
        cityDaoConfig.getIdentityScope().clear();
    }

    public PrivinceCityDao getPrivinceCityDao() {
        return privinceCityDao;
    }

    public CityDao getCityDao() {
        return cityDao;
    }

}
