package de.greendao.daoexample;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PRIVINCE_CITY.
 */
public class PrivinceCity {

    private Long id;
    /** Not-null value. */
    private String countyName;
    private String countyCode;
    private Long cityId;

    public PrivinceCity() {
    }

    public PrivinceCity(Long id) {
        this.id = id;
    }

    public PrivinceCity(Long id, String countyName, String countyCode, Long cityId) {
        this.id = id;
        this.countyName = countyName;
        this.countyCode = countyCode;
        this.cityId = cityId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCountyName() {
        return countyName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCountyName(String countyName) {
        this.countyName = countyName;
    }

    public String getCountyCode() {
        return countyCode;
    }

    public void setCountyCode(String countyCode) {
        this.countyCode = countyCode;
    }

    public Long getCityId() {
        return cityId;
    }

    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

}
